version: '3'
services:
  frontend:
    #build: ./frontend
    image: frikky/shuffle:frontend
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    #build: ./backend
    image: frikky/shuffle:backend
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    # Here for debugging:
    ports:
      - "${BACKEND_PORT}:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_HOTLOAD_LOCATION}:/shuffle-apps
    environment:
      - DATASTORE_EMULATOR_HOST=shuffle-database:8000
      - APP_HOTLOAD_FOLDER=/shuffle-apps
      - ORG_ID=${ORG_ID}
      - APP_DOWNLOAD_LOCATION=${APP_DOWNLOAD_LOCATION}
      - SHUFFLE_DEFAULT_USERNAME=${SHUFFLE_DEFAULT_USERNAME}
      - SHUFFLE_DEFAULT_PASSWORD=${SHUFFLE_DEFAULT_PASSWORD}
      - SHUFFLE_DEFAULT_APIKEY=${SHUFFLE_DEFAULT_APIKEY}
      - HTTP_PROXY=${SHUFFLE_HTTP_PROXY}
      - HTTPS_PROXY=${SHUFFLE_HTTPS_PROXY}
    restart: unless-stopped
    depends_on:
      - database
  orborus:
    #build: ./functions/onprem/orborus
    image: frikky/shuffle:orborus
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ORG_ID=${ORG_ID}
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - BASE_URL=http://${OUTER_HOSTNAME}:${BACKEND_PORT}
      - DOCKER_API_VERSION=1.40
      - HTTP_PROXY=${SHUFFLE_HTTP_PROXY}
      - HTTPS_PROXY=${SHUFFLE_HTTPS_PROXY}
      - SHUFFLE_PASS_WORKER_PROXY=${SHUFFLE_PASS_WORKER_PROXY}
    restart: unless-stopped
  database:
    #build: ./backend/database
    image: frikky/shuffle:database
    container_name: shuffle-database
    hostname: shuffle-database
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ${DB_LOCATION}:/etc/shuffle
