swagger: "3.0"
info:
  title: Slack
  description: To send message on Slack Channel
  version: "1.0"
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK4AAACuCAYAAACvDDbuAAAJ1UlEQVR4Xu2dX4hcVx3Hv2f2TxObbSiEsiZIsbVsK0WU3bmTTQqtVUuLQhAppo1Q7ENtFbFV8aGlqBAfRKOpSNWC+hKJ9sW+tLYg3bSZczfEtL6I/1BRQh6kunPvJEba3Zmf3HVbjGwy986555x7cr7zsg9zfv8+58Nw986dexX4IoEACagAe2bLJACKSwmCJEBxg9w2Nk1x6UCQBChukNvGpikuHQiSAMUNctvYNMWlA0ESoLhBbhubprh0IEgCFDfIbWPTFJcOBEmA4ga5bWya4tKBIAlQ3CC3jU1TXDoQJAGKG+S2sWmKSweCJEBxg9w2Nk1x6UCQBChukNvGpikuHQiSAMUNctvYNMWlA0ESoLhBbhubprh0IEgCFDfIbWPTFJcOBEmA4ga5bWya4tKBIAlQ3CC3Ld6mE91fVGr4OMWN14GgJm+fPDerVle/CagDReMUN6jti6/Z25Zk8vx0/yFADgK46k0CFDc+F4KZuHMiv0EGchTA/P83TXGD2ca4Gk3S/B6IPAVg22aTU9y4fGj8tIvp6a1rMnNYAQ9cqlmK2/itjKfB+aX+jsnp4bMCJKOmprijCPF9JwT26N61a1AvAJgrU5DilqHENVYJLOiVm1toPQ9gV9lCFLcsKa6zQmBD2pcBXF2lAMWtQotrayVQHB6sopUqyM6qiSluVWJcXwuB4h+xielht+wxLc/j1oKdSUwIFKe8hjJzrMzZg4vV4SeuyQ4wdiwCbZ39YNR52lGJKe4oQny/VgJJmt8LkZ+YJqW4pgQZX5rAQrc/18LwFShcWTroIgsprilBxpci8N+rvPJfAXhvqYARiyhuHRSZYySBpNt7BEp9a+TCkgsobklQXDY+gcX0H7sGMvn7i13pNU5mijsONcZUItDR2U8F+HilIB4q1ImLuaoS6BxfuUVareNV40at5yfuKEJ834hAorPiiq87jJJsEkxx6ybKfG8RaOu8rSAnbSChuDaoMuc6gUTnzwCyzwYOimuDKnNi9/LZm4bDwW9toaC4tshGnrfdzb6hFL5oCwPFtUU24rzr35JN5aehMGsLA8W1RTbivO00v1OJ/MImAoprk26kuds6O6qA/TbHp7g26UaYe/6UTE28nq/U+fXuZhgpboRy2Ry50813i5JlmzWK3BTXNuHI8ifd7FEofM322BTXNuHI8ic6+yWAD9gem+LaJhxR/o3j2z6ALbbHpri2CUeUfz7t3zghw9+5GJniuqAcSY2O7u0TqGdcjEtxXVCOpEaisy8B+LqLcSmuC8qR1Gjr7EcK+KSLcSmuC8qR1Eh0dgzArS7GpbguKEdSI9HZr+v6+fkoZBR3FCG+X5pAorM/Abi+dIDBQoprAI+hFxJIdPZ3ANe44EJxXVCOpEais/MAtroYl+K6oBxJjURnAwAtF+NSXBeUI6mR6Kz4unfGxbgU1wXlSGq0dX5mnNvij4OH4o5DjTGbEkh0VtwfrNTjnkwRUlxTgox/i0Cis+I2ogsukFBcF5QjqdFJs+dEcJeLcSmuC8qR1Gjr/LCCfM7FuBTXBeVIaiTd7EEofM/FuBTXBeVIanS6vfeLUi+6GJfiuqAcSY293dd2rqqpMy7GpbguKMdSQ0QlaXYGUG+3PTLFtU04svyJ7h0B1AHbY1Nc24Qjy99Je/eLqB/aHpvi2iYcWf7kpeydmMRfbI9NcW0TjjB/orM/A7jO5ugU1ybdSHMnOituwfSozfEprk26keZef2avGhYX3Fh7UVxraONOnKTZCQg6tihQXFtkI8/b1tlDCnjSFgaKa4ts5HnnT61sn3i99TcA222goLg2qDLnOoFEZwcBPGYDB8W1QZU51wnML/V3TEwPi0/dt9WNhOLWTZT5LiCQ6PwQIJ+vGwvFrZso811AoH3y3KxaXftj3b/+pbgUzTqBTtp7WER9u85CFLdOmsy1KYGNJ02+AoX31IWI4tZFknkuSaCd9vcoGeq6MFHcukgyz0gC7W7vu0qpz4xcWGIBxS0BiUvqIXDbkmw5P52nAN5nmpHimhJkfCUCi2n+roHIq6ZnGShuJexcXAeBJM3uhuBpk1wU14QeY8cmkOjeVwD15XETUNxxyTHOjEDxi+Dl/EkIHhwnEcUdhxpjaiFw99My8ddd+c8U8LGqCSluVWJcXyuB9TMNU/nPoXBnlcQUtwotrrVC4N2/keltWf5jKNxbtgDFLUuK6+wSEGm1df+QUvJwmUIUtwwlrnFDQER1lvMviKw/D/iSD0GhuG62hFUqEGinvVuV4Oil7kFGcSsA5VJ3BPbos9esYnBEAR/arCrFdbcXrFSVQHHcm2aPKFFfhcKV/xtOcavC5HrnBNov/fMdamLiCSh89M3iFNf5NrDguAQSnX8YkCeKB11T3HEpMs4LgeLXFP+a7u+nuF7ws6gpAYprSpDxXghQXC/YWdSUAMU1Jch4LwQorhfsLGpKgOKaEmS8FwIU1wt2FjUlQHFNCTLeCwGK6wU7i5oSoLimBBnvhQDF9YKdRU0JUFxTgoz3QoDiesHOoqYEKK4pQcZ7IUBxvWBnUVMCFNeUIOO9EKC4XrCzqCkBimtKkPFeCFBcL9hZ1JQAxTUlyHgvBCiuF+wsakqA4poSZLwXAhTXC3YWNSVAcU0JMt4LAYrrBTuLmhKguKYEGe+FAMX1gp1FTQlQXFOCjPdCgOJ6wc6ipgSiF3f+lEzhjbPXT8pgTqDmBLhRAdcB2L7xvNmZjb9bTWEzvj4C0Ylb3Kby31P9BYHcDoXbAewFsKU+pMzkgkAU4q7fU/WK/gchcp8CPgJgmwu4rGGPwGUt7u7lszcNBoP7FfAJKMzaw8jMrglcluK2dd5WwGOA7HMNlPXcELisxO0cX7lFWq3HAdzhBh+r+CJwWYi7t/vazjfU1CEF7PcFknXdEgha3I0HWXxaQQ5unLJyS4/VvBEIVtzOifwGGchRAPPe6LGwNwJBipuk+T0QeYqntbx5471wUOIupqe3rsnMYQU84J0cG/BKIBhx55f6Oyanh88KkHglxuKNIBCEuHt079o1qBcAzDWCGpvwTqDx4i7olZtbaD0PYJd3WmygMQQaLe6GtC8DuLoxxNhIIwg0Vtzi8GAVrVRBdjaCFJtoFIFGilv8IzYxPezymLZRrjSqmcaJW5zyGsrMMZ49aJQnjWumceIm3ez7UPhU40ixoUYRaJS4HZ3vF6x/jcsXCVySQGPE3bj24FV+jUtjyxBohLjFVV7np/MTvGCmzJZxTUGgEeImOv8sIN/hlpBAWQLexW2fPDerVtf+AOCqsk1zHQl4FzfRvSOAOsCtIIEqBLyKm+j+IjBMqzTMtSTg/Ri3k2bPieAubgUJVCXwH4aM5whRtJmgAAAAAElFTkSuQmCC
  contact:
    name: "@frikkylikeme"
    url: https://twitter.com/frikkylikeme
    email: frikky@shuffler.io
servers:
  - url: https://slack.com/api
host: slack.com
basePath: /api
schemes:
  - "https:"
paths:
  /chat.postMessage:
    post:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Send Message
      operationId: Send_Message
      description: ""
      parameters:
        - in: body
          name: body
          multiline: true
          description: Generated by shuffler.io OpenAPI
          required: false
          example: |-
            {
            "channel":"${channel_id}",
            "text":"${message}"
            }
          schema:
            type: string
        - in: header
          name: Content-Type
          multiline: false
          description: Header generated by shuffler.io OpenAPI
          required: false
          example: application/json;charset
          schema:
            type: string
      requestBody:
        description: Generated by Shuffler.io
        required: false
        content:
          example:
            example: |-
              {
              "channel":"${channel_id}",
              "text":"${message}"
              }
  /conversations.list:
    get:
      responses:
        default:
          description: default
          content:
            text/plain:
              schema:
                type: string
                example: ""
      summary: Channel List
      operationId: Channel_List
      description: GET channel list
      parameters: []
      requestBody:
        content: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: UUID
